basePath: /api
definitions:
  models.Employee:
    properties:
      birth_date:
        type: string
      id:
        type: integer
      name:
        type: string
      surname:
        type: string
    type: object
  models.SignUpRequest:
    properties:
      birth_date:
        type: string
      email:
        type: string
      name:
        type: string
      password:
        type: string
      surname:
        type: string
    type: object
  models.SubscriptionRequest:
    properties:
      id_to:
        type: integer
    type: object
  models.User:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a server for birthday notifications.
  title: Birthday Notification API
  version: "1.0"
paths:
  /auth/signin:
    post:
      consumes:
      - application/json
      description: Authenticate a user and return a token
      parameters:
      - description: User credentials
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: Token
          schema:
            type: string
        "400":
          description: Invalid request
          schema:
            type: string
      summary: Sign in a user
      tags:
      - auth
  /auth/signup:
    post:
      consumes:
      - application/json
      description: Create a new user and employee profile
      parameters:
      - description: Sign Up Request
        in: body
        name: signup
        required: true
        schema:
          $ref: '#/definitions/models.SignUpRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Token
          schema:
            type: string
        "400":
          description: Invalid request
          schema:
            type: string
      summary: Sign up a new user
      tags:
      - auth
  /employee/list:
    get:
      description: Retrieve a list of all employees
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Employee'
            type: array
        "500":
          description: Internal server error
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Get list of employees
      tags:
      - employee
  /employee/subscribe:
    post:
      consumes:
      - application/json
      description: Subscribe to notifications for an employee's birthday
      parameters:
      - description: Subscription details
        in: body
        name: subscription
        required: true
        schema:
          $ref: '#/definitions/models.SubscriptionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: subscription subscribed
          schema:
            type: string
        "400":
          description: Invalid request
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Subscribe to employee notifications
      tags:
      - employee
  /employee/unsubscribe:
    post:
      consumes:
      - application/json
      description: Unsubscribe from notifications for an employee's birthday
      parameters:
      - description: Subscription details
        in: body
        name: subscription
        required: true
        schema:
          $ref: '#/definitions/models.SubscriptionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: subscription unsubscribed
          schema:
            type: string
        "400":
          description: Invalid request
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Unsubscribe from employee notifications
      tags:
      - employee
securityDefinitions:
  ApiKeyAuth:
    in: cookie
    name: jwt-birthday-service
    type: apiKey
swagger: "2.0"
